primeiros testes
codenation-dev/squad-1-ad-nodejs-kroton-1 pull request #1
Opened 2020-03-07 17:03 UTC by Alissonfelipe1234

Base para testes unitarios do projeto

2020-03-07 17:13 UTC, ArturoBatistute commented on test/app.test.js
> +})
Comando para limpar o **DB** de testes **antes** de iniciar os testes

2020-03-07 17:15 UTC, ArturoBatistute commented on test/app.test.js
> +})
Comando para limpar o **DB** de testes **depois** de iniciar os testes

2020-03-07 17:29 UTC, ArturoBatistute commented on test/app.test.js
> +    expect(res.body.total).toBe(10)
10 é igual logs_tests.lenght. Esperamos que o 'total' de logs seja 10, vista que é somente um teste.

2020-03-07 17:31 UTC, ArturoBatistute commented on test/app.test.js
> +  })
10 é igual logs_tests.lenght. Esperamos que o 'total' de logs seja 10, vista que é somente um teste.

2020-03-07 17:43 UTC, ArturoBatistute commented on test/app.test.js
> +  })
```suggestion
  afterEach(async () => {
    clearDB()
  })
```

2020-03-07 17:53 UTC, ArturoBatistute commented on test/app.test.js
> +
```suggestion
const clearDB = async () => {
  await db.sequelize.query('SET FOREIGN_KEY_CHECKS = 0;')
  await db.sequelize.query('TRUNCATE TABLE logs;')
  await db.sequelize.query('TRUNCATE TABLE users;')  
  await db.sequelize.query('TRUNCATE TABLE log_levels;')
  await db.sequelize.query('SET FOREIGN_KEY_CHECKS = 1;')
}
```

2020-03-07 17:54 UTC, ArturoBatistute commented on test/app.test.js
> +  })
```suggestion
  afterEach(async () => {
    clearDB()
  })
```

2020-03-07 17:55 UTC, ArturoBatistute commented on test/app.test.js
> +  })
```suggestion
  afterEach(async () => {
    clearDB()
  })
```

2020-03-07 19:02 UTC, ArturoBatistute commented on test/app.test.js
> +    expect(res.body.logs).toBeDefined()
```suggestion
   expect(res.body.logs).toMatchObject(logs_tests)
```

2020-03-07 19:03 UTC, ArturoBatistute commented on test/app.test.js
> +    // ...
```suggestion
    const res = await request(server.app).get('/logs')
    expect(res.body.logs).toEqual(logs_tests)
```

2020-03-07 19:08 UTC, ArturoBatistute commented on test/app.test.js
> +    expect(res.body.total).toBe(10)
10 é igual logs_tests.lenght. Esperamos que o 'total' de logs seja 10, vista que é somente um teste.

2020-03-07 19:10 UTC, ArturoBatistute requested changes
Some changes to be done!
Tks
 @Alissonfelipe1234

2020-03-16 12:25 UTC, Alissonfelipe1234 commented
> signin e login é a mesma coisa, a gente podia usar **signup** e **signin** ou **cadastro** e **login**

Ajustes feitos

2020-03-17 18:10 UTC, merged